services:
  folia:
    image: itzg/minecraft-server:latest
    environment:
      EULA: "TRUE"
      TYPE: "FOLIA"
      VERSION: "1.21.11"
      MEMORY: "2G"
      ONLINE_MODE: "false"
      ENABLE_COMMAND_BLOCK: "true"
      COPY_PLUGINS_SRC: "/plugins"
      COPY_PLUGINS_DEST: "/data/plugins"
    ports:
      - "25565:25565"
    volumes:
      - ./output/target/OreAnnouncer-2.8.5.jar:/plugins/OreAnnouncer.jar:ro
      - folia-data:/data
    stdin_open: true
    tty: true

volumes:
  folia-data:
